// Package vdbe implements the Virtual Database Engine for sqlite-go.
// The VDBE is a register-based virtual machine that executes bytecode
// programs generated by the SQL compiler.
package vdbe

// Opcode represents a VDBE instruction opcode.
type Opcode int

// All VDBE opcodes, mirroring SQLite's opcodes.
const (
	OpAbortable      Opcode = iota
	OpAdd
	OpAddImm
	OpAggFinal
	OpAggInverse
	OpAggStep
	OpAggValue
	OpAnd
	OpAutoCommit
	OpBeginSubrtn
	OpBitAnd
	OpBitNot
	OpBitOr
	OpBlob
	OpCast
	OpCheckpoint
	OpClear
	OpClose
	OpCollSeq
	OpColumn
	OpCompare
	OpConcat
	OpCopy
	OpCreateBTree
	OpCrossjoin
	OpDecrJumpZero
	OpDelete
	OpDestroy
	OpDivide
	OpDropIndex
	OpDropTable
	OpDropTrigger
	OpElseEq
	OpEndCoroutine
	OpEq
	OpExpire
	OpExplain
	OpFilter
	OpFirst
	OpFkCheck
	OpFkCounter
	OpFkIfZero
	OpFound
	OpFunction
	OpGe
	OpGoSub
	OpGoto
	OpGt
	OpHalt
	OpHaltIfNull
	OpIdxDelete
	OpIdxGE
	OpIdxGT
	OpIdxInsert
	OpIdxLE
	OpIdxLT
	OpIdxRowid
	OpIf
	OpIfNot
	OpIfNotOpen
	OpIfNullRow
	OpIfPos
	OpIncrVacuum
	OpInit
	OpInitCoroutine
	OpInteger
	OpInsert
	OpInt64
	OpIntCmp
	OpInterrupt
	OpIsNull
	OpJournalMode
	OpJump
	OpLast
	OpLe
	OpLoadAnalysis
	OpLt
	OpMakeRecord
	OpMaxPgcnt
	OpMove
	OpMul
	OpMustBeInt
	OpNe
	OpNewRowid
	OpNext
	OpNoConflict
	OpNoop
	OpNot
	OpNotNull
	OpNotExists
	OpNotFound
	OpNull
	OpNullRow
	OpOffset
	OpOnce
	OpOpenAutoindex
	OpOpenDup
	OpOpenEphemeral
	OpOpenPseudo
	OpOpenRead
	OpOpenWrite
	OpOr
	OpPagecount
	OpParam
	OpParseSchema
	OpPermutation
	OpPrev
	OpProgram
	OpReadCookie
	OpReal
	OpRelease
	OpRemainder
	OpResetCount
	OpResetSorter
	OpResultRow
	OpReturn
	OpRewind
	OpRowCell
	OpRowData
	OpRowid
	OpRowSetAdd
	OpRowSetRead
	OpRowSetTest
	OpSavepoint
	OpSCopy
	OpSeek
	OpSeekGE
	OpSeekGT
	OpSeekHit
	OpSeekLE
	OpSeekLT
	OpSeekScan
	OpSequence
	OpSequenceTest
	OpSetCookie
	OpShiftLeft
	OpShiftRight
	OpSort
	OpSorterCompare
	OpSorterData
	OpSorterInsert
	OpSorterNext
	OpSorterOpen
	OpSorterSort
	OpString
	OpString8
	OpSubtract
	OpTableLock
	OpTableUnlock
	OpTrace
	OpTransaction
	OpTrim
	OpTypeCheck
	OpUnique
	OpUpdate
	OpVacuum
	OpVariable
	OpVBegin
	OpVCheck
	OpVColumn
	OpVCreate
	OpVDestroy
	OpVFilter
	OpVIn
	OpVNext
	OpVOpen
	OpVRename
	OpVUpdate
	OpYield
)

// Instruction represents a single VDBE instruction.
type Instruction struct {
	Op      Opcode      // Operation code
	P1      int         // First parameter
	P2      int         // Second parameter (often a jump target)
	P3      int         // Third parameter
	P4      interface{} // Fourth parameter (varies by opcode)
	P5      int         // Fifth parameter (flags)
	Comment string      // Comment for debugging
}

// SerialType represents a record serial type.
type SerialType int

const (
	SerialNull    SerialType = 0
	SerialInt8    SerialType = 1
	SerialInt16   SerialType = 2
	SerialInt24   SerialType = 3
	SerialInt32   SerialType = 4
	SerialInt48   SerialType = 5
	SerialInt64   SerialType = 6
	SerialFloat64 SerialType = 7
	SerialZero    SerialType = 8
	SerialOne     SerialType = 9
	SerialBlob    SerialType = 12
	SerialText    SerialType = 13
)
