// Package vdbe implements the Virtual Database Engine for sqlite-go.
// The VDBE is a register-based virtual machine that executes bytecode
// programs generated by the SQL compiler.
package vdbe

// Opcode represents a VDBE instruction opcode.
type Opcode int

// All VDBE opcodes, mirroring SQLite's opcodes.
const (
	OpAbortable      Opcode = iota
	OpAdd                                    // r[r[1]] = r[r[2]] + r[r[3]]
	OpAddImm                                 // r[r[1]] += r[2]
	OpAggFinal                               // Finalize aggregate
	OpAggInverse                             // Inverse aggregate step
	OpAggStep                                // Add row to aggregate
	OpAggValue                               // Read aggregate value
	OpAnd                                    // r[r[1]] = r[r[2]] AND r[r[3]]
	OpAutoCommit                              // Commit or rollback transaction
	OpBeginSubrtn                             // Begin subroutine
	OpBitAnd                                 // r[r[1]] = r[r[2]] & r[r[3]]
	OpBitNot                                 // r[r[1]] = ~r[r[1]]
	OpBitOr                                  // r[r[1]] = r[r[2]] | r[r[3]]
	OpBlob                                   // r[r[1]] = blob(P4)
	OpCast                                   // Cast r[r[1]] to type P2
	OpCheckpoint                              // Checkpoint WAL
	OpClear                                   // Clear table
	OpClose                                  // Close cursor
	OpCollSeq                                // Set collation sequence
	OpColumn                                 // Read column from cursor
	OpCompare                                // Compare two registers
	OpConcat                                 // r[r[1]] = r[r[2]] || r[r[3]]
	OpCopy                                   // Copy register range
	OpCreateBTree                            // Create new B-Tree
	OpCrossjoin                              // Cross-join optimization
	OpDecrJumpZero                           // Decrement and jump if zero
	OpDelete                                 // Delete cursor row
	OpDestroy                                // Drop B-Tree
	OpDivide                                 // r[r[1]] = r[r[2]] / r[r[3]]
	OpDropIndex                              // Drop index entry
	OpDropTable                              // Drop table entry
	OpDropTrigger                            // Drop trigger entry
	OpElseEq                                 // Else-eq jump
	OpEndCoroutine                           // End coroutine
	OpEq                                     // Jump if equal
	OpExpire                                 // Expire prepared statements
	OpExplain                                // Explain instruction
	OpFilter                                 // Filter rows
	OpFirst                                  // Move cursor to first
	OpFkCheck                                // Foreign key check
	OpFkCounter                              // FK constraint counter
	OpFkIfZero                               // FK check if zero
	OpFound                                  // Jump if found
	OpFunction                               // Call function
	OpGe                                     // Jump if >=
	OpGoSub                                  // Go to subroutine
	OpGoto                                   // Unconditional jump
	OpGt                                     // Jump if >
	OpHalt                                   // Halt program
	OpHaltIfNull                             // Halt if null
	OpIdxDelete                              // Delete index entry
	OpIdxGE                                  // Index >= comparison
	OpIdxGT                                  // Index > comparison
	OpIdxInsert                              // Insert index entry
	OpIdxLE                                  // Index <= comparison
	OpIdxLT                                  // Index < comparison
	OpIdxRowid                               // Get rowid from index cursor
	OpIf                                     // Jump if true
	OpIfNot                                  // Jump if false
	OpIfNotOpen                              // Jump if cursor not open
	OpIfNullRow                              // Jump if null row
	OpIfPos                                  // Jump if positive
	OpIncrVacuum                             // Incremental vacuum
	OpInit                                   // Initialize and jump
	OpInitCoroutine                          // Initialize coroutine
	OpInsert                                 // Insert row
	OpInt64                                  // r[r[1]] = P2 (int64)
	OpIntCmp                                 // Integer comparison
	OpInterrupt                              // Check for interrupt
	OpIsNull                                 // Jump if null
	OpJournalMode                            // Set journal mode
	OpJump                                   // Jump based on comparison
	OpLast                                   // Move cursor to last
	OpLe                                     // Jump if <=
	OpLoadAnalysis                           // Load analysis data
	OpLt                                     // Jump if <
	OpMakeRecord                             // Create record from registers
	OpMaxPgcnt                               // Set max page count
	OpMove                                   // Move register
	OpMul                                    // r[r[1]] = r[r[2]] * r[r[3]]
	OpMustBeInt                              // Ensure register is integer
	OpNe                                     // Jump if not equal
	OpNewRowid                               // Get new rowid
	OpNext                                   // Move cursor to next
	OpNoConflict                             // No conflict check
	OpNot                                    // r[r[1]] = !r[r[2]]
	OpNotNull                                // Jump if not null
	OpNotExists                              // Jump if rowid not exists
	OpNotFound                               // Jump if not found
	OpNull                                   // Set register to NULL
	OpNullRow                                // Move cursor to null row
	OpOffset                                 // Read column with offset
	OpOnce                                   // Execute only once
	OpOpenAutoindex                          // Open autoindex cursor
	OpOpenDup                                // Open duplicate cursor
	OpOpenEphemeral                          // Open ephemeral B-Tree
	OpOpenPseudo                             // Open pseudo cursor
	OpOpenRead                               // Open cursor for reading
	OpOpenWrite                              // Open cursor for writing
	OpOr                                     // r[r[1]] = r[r[2]] OR r[r[3]]
	OpPagecount                              // Return page count
	OpParam                                  // Set parameter
	OpParseSchema                            // Parse schema entry
	OpPermutation                            // Set column permutation
	OpPrev                                   // Move cursor to previous
	OpProgram                                // Run sub-program
	OpReadCookie                             // Read schema cookie
	OpReal                                   // r[r[1]] = P4 (float)
	OpRelease                                // Release savepoint
	OpRemainder                              // r[r[1]] = r[r[2]] % r[r[3]]
	OpResetCount                             // Reset change counter
	OpResetSorter                            // Reset sorter cursor
	OpResultRow                              // Output result row
	OpReturn                                 // Return from subroutine
	OpRewind                                 // Rewind cursor to beginning
	OpRowCell                                // Read cell
	OpRowData                                // Read row data
	OpRowid                                  // Get cursor rowid
	OpRowSetAdd                              // Add to row set
	OpRowSetRead                             // Read from row set
	OpRowSetTest                             // Test row set membership
	OpSavepoint                              // Start savepoint
	OpSCopy                                  // Scalar copy register
	OpSeek                                   // Seek cursor to rowid
	OpSeekGE                                 // Seek >=
	OpSeekGT                                 // Seek >
	OpSeekHit                                // Seek hit marker
	OpSeekLE                                 // Seek <=
	OpSeekLT                                 // Seek <
	OpSeekScan                               // Seek + scan
	OpSequence                               // Autoincrement sequence
	OpSequenceTest                           // Test sequence
	OpSetCookie                              // Set schema cookie
	OpShiftLeft                              // r[r[1]] = r[r[2]] << r[r[3]]
	OpShiftRight                             // r[r[1]] = r[r[2]] >> r[r[3]]
	OpSort                                   // Sort sorter cursor
	OpSorterCompare                          // Compare for sorter
	OpSorterData                             // Read from sorter
	OpSorterInsert                           // Insert into sorter
	OpSorterNext                             // Next from sorter
	OpSorterOpen                             // Open sorter
	OpSorterSort                             // Sort sorter
	OpString                                 // r[r[1]] = P4 (string)
	OpString8                                // r[r[1]] = P4 (string, UTF-8)
	OpSubtract                               // r[r[1]] = r[r[2]] - r[r[3]]
	OpTableLock                              // Lock table
	OpTableUnlock                            // Unlock table
	OpTrace                                  // Trace output
	OpTransaction                            // Begin transaction
	OpTrim                                   // Trim function
	OpTypeCheck                              // Type check
	OpUnique                                 // Unique constraint check
	OpUpdate                                 // Update row
	OpVacuum                                 // Vacuum database
	OpVariable                               // Read SQL variable
	OpVBegin                                 // Virtual table begin
	OpVCheck                                 // Virtual table check
	OpVColumn                                // Virtual table column
	OpVCreate                                // Create virtual table
	OpVDestroy                               // Destroy virtual table
	OpVFilter                                // Virtual table filter
	OpVIn                                    // Virtual table IN constraint
	OpVNext                                  // Virtual table next
	OpVOpen                                  // Open virtual table
	OpVRename                                // Rename virtual table
	OpVUpdate                                // Update virtual table
	OpYield                                  // Yield from coroutine
)

// Instruction represents a single VDBE instruction.
type Instruction struct {
	Op      Opcode     // Operation code
	P1      int        // First parameter
	P2      int        // Second parameter (often a jump target)
	P3      int        // Third parameter
	P4      interface{} // Fourth parameter (varies by opcode)
	P5      int        // Fifth parameter (flags)
	Comment string     // Comment for debugging
}

// SerialType represents a record serial type.
type SerialType int

const (
	SerialNull    SerialType = 0
	SerialInt8    SerialType = 1
	SerialInt16   SerialType = 2
	SerialInt24   SerialType = 3
	SerialInt32   SerialType = 4
	SerialInt48   SerialType = 5
	SerialInt64   SerialType = 6
	SerialFloat64 SerialType = 7
	SerialZero    SerialType = 8
	SerialOne     SerialType = 9
	SerialBlob    SerialType = 12 // + N*2 for blob of length N
	SerialText    SerialType = 13 // + N*2 for text of length N
)

// MemType represents the type of a VDBE memory cell.
type MemType int

const (
	MemNull    MemType = 0
	MemInt     MemType = 1
	MemFloat   MemType = 2
	MemText    MemType = 3
	MemBlob    MemType = 4
	MemUndefined MemType = 5
)
